In [223]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix, accuracy_score, recall_score, classification_report)

In [224]:
test = pd.read_csv('E-Commerce_test.csv', delimiter=';')
test

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0      9000               F             Ship                    5   
1      9001               D             Ship                    5   
2      9002               F             Ship                    3   
3      9003               A             Ship                    5   
4      9004               B             Ship                    4   
...     ...             ...              ...                  ...   
1995  10995               A             Ship                    4   
1996  10996               B             Ship                    4   
1997  10997               C             Ship                    5   
1998  10998               F             Ship                    5   
1999  10999               D             Ship                    2   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                   1                  189                2   
1                   3                  150                2   
2                   3                  200                3   
3                   1                  133                2   
4                   2                  260                3   
...               ...                  ...              ...   
1995                1                  252                5   
1996                1                  232                5   
1997                4                  242                5   
1998                2                  223                6   
1999                5                  155                5   

     Product_importance Gender  Discount_offered  Weight_in_gms  
0                medium      M                10           5248  
1                  high      F                 9           4446  
2                   low      M                 3           5739  
3                medium      M                 1           4643  
4                   low      M                 4           5504  
...                 ...    ...               ...            ...  
1995             medium      F                 1           1538  
1996             medium      F                 6           1247  
1997                low      F                 4           1155  
1998             medium      M                 2           1210  
1999                low      F                 6           1639  

[2000 rows x 11 columns]

In [225]:
train = pd.read_csv('E-Commerce_train.csv', delimiter=';')
train

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0        1               D           Flight                    4   
1        2               F           Flight                    4   
2        3               A           Flight                    2   
3        4               B           Flight                    3   
4        5               C           Flight                    2   
...    ...             ...              ...                  ...   
8994  8995               D             Ship                    3   
8995  8996               F             Ship                    5   
8996  8997               A             Ship                    4   
8997  8998               B             Ship                    4   
8998  8999               C             Ship                    5   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                   2                  177                3   
1                   5                  216                2   
2                   2                  183                4   
3                   3                  176                4   
4                   2                  184                3   
...               ...                  ...              ...   
8994                1                  217                3   
8995                3                  232                3   
8996                5                  260                3   
8997                2                  184                3   
8998                4                  145                4   

     Product_importance Gender  Discount_offered  Weight_in_gms  \
0                   low      F                44           1233   
1                   low      M                59           3088   
2                   low      M                48           3374   
3                medium      M                10           1177   
4                medium      F                46           2484   
...                 ...    ...               ...            ...   
8994                low      F                 1           4177   
8995             medium      M                 3           4526   
8996             medium      F                 6           4221   
8997             medium      F                 5           5931   
8998                low      M                 4           4790   

      Reached.on.Time_Y.N  
0                       1  
1                       1  
2                       1  
3                       1  
4                       1  
...                   ...  
8994                    1  
8995                    0  
8996                    0  
8997                    1  
8998                    0  

[8999 rows x 12 columns]

In [226]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   2000 non-null   int64 
 1   Warehouse_block      2000 non-null   object
 2   Mode_of_Shipment     2000 non-null   object
 3   Customer_care_calls  2000 non-null   int64 
 4   Customer_rating      2000 non-null   int64 
 5   Cost_of_the_Product  2000 non-null   int64 
 6   Prior_purchases      2000 non-null   int64 
 7   Product_importance   2000 non-null   object
 8   Gender               2000 non-null   object
 9   Discount_offered     2000 non-null   int64 
 10  Weight_in_gms        2000 non-null   int64 
dtypes: int64(7), object(4)
memory usage: 172.0+ KB


In [227]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   8999 non-null   int64 
 1   Warehouse_block      8999 non-null   object
 2   Mode_of_Shipment     8999 non-null   object
 3   Customer_care_calls  8999 non-null   int64 
 4   Customer_rating      8999 non-null   int64 
 5   Cost_of_the_Product  8999 non-null   int64 
 6   Prior_purchases      8999 non-null   int64 
 7   Product_importance   8999 non-null   object
 8   Gender               8999 non-null   object
 9   Discount_offered     8999 non-null   int64 
 10  Weight_in_gms        8999 non-null   int64 
 11  Reached.on.Time_Y.N  8999 non-null   int64 
dtypes: int64(8), object(4)
memory usage: 843.8+ KB


Consultamos si hay registros duplicados y los imprimimos

In [228]:
test[test.duplicated()]
print("La cantidad de registros duplicados es de: ", test.duplicated().sum())

La cantidad de registros duplicados es de:  0


In [229]:
train[train.duplicated()]
print("La cantidad de registros duplicados es de: ", train.duplicated().sum())

La cantidad de registros duplicados es de:  0


In [230]:
test.describe()

ID  Customer_care_calls  Customer_rating  \
count   2000.000000          2000.000000       2000.00000   
mean    9999.500000             4.231500          2.97050   
std      577.494589             1.136465          1.41585   
min     9000.000000             2.000000          1.00000   
25%     9499.750000             3.000000          2.00000   
50%     9999.500000             4.000000          3.00000   
75%    10499.250000             5.000000          4.00000   
max    10999.000000             7.000000          5.00000   

       Cost_of_the_Product  Prior_purchases  Discount_offered  Weight_in_gms  
count          2000.000000       2000.00000        2000.00000     2000.00000  
mean            217.555000          3.82000           5.61400     3857.42650  
std              46.336276          1.45453           2.90469     1707.78448  
min              96.000000          2.00000           1.00000     1003.00000  
25%             179.750000          3.00000           3.00000     1773.75000  
50%             226.000000          4.00000           6.00000     4536.00000  
75%             255.000000          5.00000           8.00000     5241.25000  
max             310.000000         10.00000          10.00000     6000.00000

In [231]:
train.describe()

ID  Customer_care_calls  Customer_rating  Cost_of_the_Product  \
count  8999.00000          8999.000000      8999.000000          8999.000000   
mean   4500.00000             4.015113         2.994999           208.561507   
std    2597.93187             1.138934         1.413143            48.289172   
min       1.00000             2.000000         1.000000            96.000000   
25%    2250.50000             3.000000         2.000000           168.000000   
50%    4500.00000             4.000000         3.000000           211.000000   
75%    6749.50000             5.000000         4.000000           249.500000   
max    8999.00000             7.000000         5.000000           310.000000   

       Prior_purchases  Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
count      8999.000000       8999.000000    8999.000000          8999.000000  
mean          3.511501         15.097678    3584.364596             0.635515  
std           1.532074         17.400040    1614.750194             0.481312  
min           2.000000          1.000000    1001.000000             0.000000  
25%           3.000000          4.000000    1857.000000             0.000000  
50%           3.000000          8.000000    4046.000000             1.000000  
75%           4.000000         19.000000    4999.500000             1.000000  
max          10.000000         65.000000    7846.000000             1.000000

In [232]:
train = train.loc[train["Discount_offered"] <= 10] #reducimos el rango de descuentos al 10%

In [233]:
#reemplazamos los valores de cada columna con el de los siguientes diccionarios para un mejor entendimiento
product_importance = {"low":1,"medium":2,"high": 3}
gender = {"F":1, "M":2}
warehouse = {"A":1,"B":2,"C":3,"D":4,"F":5}
shipment = {"Road":1, "Flight":2, "Ship":3}

new_train = train.replace({"Product_importance":product_importance, "Gender":gender, "Warehouse_block":warehouse, 'Mode_of_Shipment': shipment})
new_train

ID  Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
3        4                2                 2                    3   
6        7                4                 2                    3   
12      13                4                 2                    3   
16      17                3                 2                    3   
22      23                3                 3                    2   
...    ...              ...               ...                  ...   
8994  8995                4                 3                    3   
8995  8996                5                 3                    5   
8996  8997                1                 3                    4   
8997  8998                2                 3                    4   
8998  8999                3                 3                    5   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
3                   3                  176                4   
6                   4                  250                3   
12                  5                  198                3   
16                  4                  143                2   
22                  5                  156                2   
...               ...                  ...              ...   
8994                1                  217                3   
8995                3                  232                3   
8996                5                  260                3   
8997                2                  184                3   
8998                4                  145                4   

      Product_importance  Gender  Discount_offered  Weight_in_gms  \
3                      2       2                10           1177   
6                      1       1                 3           2371   
12                     2       1                 1           3667   
16                     2       1                 6           1194   
22                     1       2                 2           1750   
...                  ...     ...               ...            ...   
8994                   1       1                 1           4177   
8995                   2       2                 3           4526   
8996                   2       1                 6           4221   
8997                   2       1                 5           5931   
8998                   1       2                 4           4790   

      Reached.on.Time_Y.N  
3                       1  
6                       1  
12                      1  
16                      1  
22                      1  
...                   ...  
8994                    1  
8995                    0  
8996                    0  
8997                    1  
8998                    0  

[6352 rows x 12 columns]

In [234]:
#eliminamos la columna ID
new_train.drop(["ID"], axis=1, inplace=True)
new_train.head()

Warehouse_block  Mode_of_Shipment  Customer_care_calls  Customer_rating  \
3                 2                 2                    3                3   
6                 4                 2                    3                4   
12                4                 2                    3                5   
16                3                 2                    3                4   
22                3                 3                    2                5   

    Cost_of_the_Product  Prior_purchases  Product_importance  Gender  \
3                   176                4                   2       2   
6                   250                3                   1       1   
12                  198                3                   2       1   
16                  143                2                   2       1   
22                  156                2                   1       2   

    Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
3                 10           1177                    1  
6                  3           2371                    1  
12                 1           3667                    1  
16                 6           1194                    1  
22                 2           1750                    1

In [235]:
#Determinando los valores a utilizar posteriormente
x = new_train.drop("Reached.on.Time_Y.N", axis="columns")
y = new_train["Reached.on.Time_Y.N"]


In [236]:
#Adopto un tamaño de testeo de 30% de los registros totales
#Adopto un numero aleatorio para el random_state, en este caso 10
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=10) #Realizamos el split

In [237]:
# x_train = np.array(x_train) #Convertimos nuestra variable en un array
# x_train
# x_train = np.array(x_train) #Convertimos nuestra variable en un array
# x_train

In [238]:
#Instanciamos el modelo en una variable
logReg = LogisticRegression()

In [239]:
#Ajustamos el modelo usando el entrenamiento
logReg = logReg.fit(x_train, y_train)

In [240]:
#Usamos el modelo para hacer predicciones del testing
y_pred = logReg.predict(x_test) #Empezamos a pronosticar por el conjunto que no fue considerado(test)
y_pred

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

In [241]:
#Diagnosticos del modelo
conf_mat = metrics.confusion_matrix(y_test, y_pred)
conf_mat
#El primer set diagonal es la pronosticación acertada, y en la segunda son equívocos.

array([[687, 321],
       [554, 344]], dtype=int64)

In [242]:
#Evaluamos la calidad del modelo
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.5409233997901364

In [243]:
test = test.loc[test["Discount_offered"] <= 10] 
product_importance = {"low":1,"medium":2,"high": 3}
gender = {"F":1, "M":2}
warehouse = {"A":1,"B":2,"C":3,"D":4,"F":5}
shipment = {"Road":1, "Flight":2, "Ship":3}

new_test = test.replace({"Product_importance":product_importance, "Gender":gender, "Warehouse_block":warehouse, 'Mode_of_Shipment': shipment})
new_test

new_test.drop(["ID"], axis=1, inplace=True)
new_test.head()

Warehouse_block  Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0                5                 3                    5                1   
1                4                 3                    5                3   
2                5                 3                    3                3   
3                1                 3                    5                1   
4                2                 3                    4                2   

   Cost_of_the_Product  Prior_purchases  Product_importance  Gender  \
0                  189                2                   2       2   
1                  150                2                   3       1   
2                  200                3                   1       2   
3                  133                2                   2       2   
4                  260                3                   1       2   

   Discount_offered  Weight_in_gms  
0                10           5248  
1                 9           4446  
2                 3           5739  
3                 1           4643  
4                 4           5504

In [244]:
scaler = StandardScaler()
new_test = scaler.fit_transform(new_test)
new_test

array([[ 1.11740536,  0.64998085,  0.67638858, ...,  1.00501256,
         1.51034956,  0.81445949],
       [ 0.44649251,  0.64998085,  0.67638858, ..., -0.99501244,
         1.16599262,  0.34472775],
       [ 1.11740536,  0.64998085, -1.083894  , ...,  1.00501256,
        -0.90014906,  1.1020384 ],
       ...,
       [-0.22442035,  0.64998085,  0.67638858, ..., -0.99501244,
        -0.55579211, -1.58281235],
       [ 1.11740536,  0.64998085,  0.67638858, ...,  1.00501256,
        -1.244506  , -1.55059882],
       [ 0.44649251,  0.64998085, -1.96403529, ..., -0.99501244,
         0.13292178, -1.29933334]])

In [246]:
resultados = logReg.predict(new_test)
resultados

c:\Users\Usuario\anaconda3\envs\fastAPI-crud-env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [249]:
prediccion = pd.DataFrame({
    "pred": resultados})

In [251]:
#Guardar archivo final
prediccion.to_csv('camilavaughan.csv', index=False)